// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzZuxbLVAW7bkMNPSdvlgoLhM2JvyuY88',
    appId: '1:11558714996:web:38e2063d31e8a7878cdb21',
    messagingSenderId: '11558714996',
    projectId: 'safetystove-3ff9e',
    authDomain: 'safetystove-3ff9e.firebaseapp.com',
    storageBucket: 'safetystove-3ff9e.appspot.com',
    measurementId: 'G-N4YTR54HPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe2mnuFS3LYJ4XJm1400D2rs4gSuM0D8E',
    appId: '1:11558714996:android:3a4e8854807c2c438cdb21',
    messagingSenderId: '11558714996',
    projectId: 'safetystove-3ff9e',
    storageBucket: 'safetystove-3ff9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4M6FzVIxUvcIxdr4G5PO27FNxHYJWfmo',
    appId: '1:11558714996:ios:067f6571eda77f398cdb21',
    messagingSenderId: '11558714996',
    projectId: 'safetystove-3ff9e',
    storageBucket: 'safetystove-3ff9e.appspot.com',
    iosBundleId: 'com.example.komporSafety',
  );
}
